require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7.2
  Excludes:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'app/controllers/graphql_controller.rb'
    - 'config/**/*'
    - 'Gemfile*'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/factories/**/*'
    - 'vendor/bundle/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Guardfile'

Rails:
  Enabled: true
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
RSpec/ExampleLength:
  Max: 10
Style/StructInheritance:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Metrics/AbcSize:
  Max: 22
