require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false

AllCops:
  Excludes:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'app/controllers/graphql_controller.rb'
    - 'config/**/*'
    - 'Gemfile*'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/factories/**/*'
    - 'vendor/bundle/**/*'
  Rails:
    Enabled: true
  Layout/LineLength:
    Max: 120
  Metrics/MethodLength:
    Max: 25
