version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
        environment:
          DATABASE_HOST: localhost
          DATABASE_USER: myapp
          DATABASE_PASSWORD: ""
          RAILS_ENV: test
      - image: circleci/postgres:11.1
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: Install bundler
          command: gem install bundler:2.1.4
      - run:
          name: Install gems
          command: bundle config set path 'vendor/bundle' && bundle install --jobs=4
      - save_cache:
          paths:
            - ./vendor/bundle
            key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Yarn setup
          command: yarn install
      - run:
          name: Database setup
          command: bundle exec rake db:setup
      - run:
          name: RSpec tests
          command: bundle exec rspec
      # - run:
      #     name: Rubocop linter/formatting
      #     command: bundle exec rubocop
