# Github action workflow name.
name: CI
# Actions workflow listens for
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Postgresql DB.
      db:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@main
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          # Uses ruby version from .ruby-version
          # Runs bundle install caching the gems
          bundler-cache: true
      # Install npm packages
      - uses: borales/actions-yarn@v2.3.0
        with: 
          cmd: install
      - name: Run rspec tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/myapp_test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails db:prepare
          rspec
